# $Id$

language: c

os:
  - linux

compiler:
 - gcc

script:
 - ./configure
 - make
 - sudo make install

notifications:
 email:
  - bugs@ircd-hybrid.org
 irc:
  channels:
  - "irc.ircd-hybrid.org#ircd-coders"
  skip_join: true
